version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: melenium_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.develop.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites
      - ./panel:/app
    depends_on:
      - php-fpm
      - node
    networks:
      - melenium_network

  php-fpm:
    build:
      context: ./panel
      dockerfile: ./Dockerfile
    container_name: melenium_panel_php
    volumes:
      - ./panel:/app
      - ./docker/panel/.env:/app/var/.env
    environment:
      DB_HOST: melenium_mariadb
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
    depends_on:
      - database
      - redis
    networks:
      - melenium_network

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: melenium_node
    volumes:
      - ./landing:/app/landing
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - melenium_network

  database:
    image: mariadb:10.6
    container_name: melenium_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - melenium_network
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: melenium_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - melenium_network

volumes:
  redis_data:

networks:
  melenium_network:
    driver: bridge